// Generated by scripts/generate_api_types.py. Do not edit.
/* eslint-disable */

export type ActiveProfileRequest = { profile_id?: string | null };

export type ActiveProfileResponse = { active_profile_id: string | null; config_revision: string };

export type AllRunsResponse = { runs: AllRunsRunModel[]; total_count: number };

export type AllRunsRunModel = { run_session_id: string; session_id: string | null; parent_run_session_id: string | null; agent_name: string | null; agent_type: string | null; provider: string | null; provider_id: string | null; profile_id: string | null; model: string | null; status: "started" | "completed" | "interrupted" | "failed" | "starting" | "running" | "waiting_for_input" | "ended" | "stale"; started_at: string; ended_at: string | null; total_duration_ms: number | null; input_tokens: number; cached_input_tokens: number; cache_write_tokens: number; cache_write_1h_tokens: number; output_tokens: number; reasoning_tokens: number; tool_use_tokens: number; provider_total_tokens: number; estimated_cost_usd: number; total_tool_calls: number; total_api_calls: number; error_count: number; kind?: string; task_id?: string | null; project_dir?: string | null; last_event_seq?: number; snapshot?: unknown | null; exit_code?: number | null; fatal_error?: string | null; metadata: unknown | null; session_title?: string | null };

export type BoardStageModel = { id: string; name: string; position: number; profile_id?: string | null; command_id?: string | null; auto_start: boolean };

export type BoardStageUpdateModel = { id?: string | null; name: string; profile_id?: string | null; command_id?: string | null; auto_start?: boolean };

export type BoardStagesResponse = { board_stages: BoardStageModel[] };

export type BoardStagesUpdatedSseEventModel = { seq: number; created_at: string; type: "board_stages_updated"; payload: BoardStagesUpdatedSseEventPayloadModel };

export type BoardStagesUpdatedSseEventPayloadModel = { board_stages: BoardStageModel[] };

export type Body_upload_saved_session_images_api_sessions__session_id__images_post = { files: string[] };

export type Body_upload_task_images_api_tasks_images_post = { files: string[] };

export type BootstrapResponse = { workspace_root: string; provider: string | null; provider_id: string | null; profile_id: string | null; model: string | null; reasoning_effort: string | null; supports_image_inputs: boolean; sessions: SessionRecordModel[]; tasks: TaskRecordModel[]; live_sessions: LiveSessionModel[]; board_stages: BoardStageModel[] };

export type CommandListResponse = { commands: CommandViewModel[]; config_revision: string };

export type CommandViewModel = { id: string; name: string; slash_alias: string; description: string; instructions: string; path: string };

export type ConfigBootstrapResponse = { providers: ProviderViewModel[]; model_profiles: ModelProfileViewModel[]; commands: CommandViewModel[]; active_profile_id: string | null; config_revision: string; options: ConfigOptionsModel };

export type ConfigOptionsModel = { provider_kinds: string[]; reasoning_efforts: string[]; openai_service_tiers: string[]; provider_metadata: Record<string, ProviderKindMetadataModel> };

export type CreateSessionRequest = { title?: string; profile_id?: string | null };

export type CreateTaskRequest = { title: string; prompt: string; stage?: string | null; project_dir?: string; session_id?: string | null; profile_id?: string | null; image_upload_ids?: string[] };

export type DailyBucketModel = { date: string; runs: number; tokens: number; cost: number; errors: number };

export type DashboardOverviewModel = { total_sessions: number; total_runs: number; total_input_tokens: number; total_cached_tokens: number; total_output_tokens: number; total_reasoning_tokens: number; total_cost: number; total_api_calls: number; total_tool_calls: number; total_errors: number; avg_duration_ms: number | null; completed_runs: number; failed_runs: number };

export type DashboardStatsResponse = { overview: DashboardOverviewModel; breakdown: ProviderBreakdownModel[]; daily: DailyBucketModel[] };

export type DiffLineNumberModel = { old?: number | null; new?: number | null };

export type EmptyPayloadModel = {  };

export type ExpandInputRequest = { text?: string };

export type ExpandInputResponse = { text: string; file_paths?: string[]; image_paths?: string[]; warnings?: string[] };

export type FileMentionItemModel = { path: string; kind: "file" | "image" };

export type FileMentionSearchResponse = { items: FileMentionItemModel[] };

export type HTTPValidationError = { detail?: ValidationError[] };

export type HistoryItemModel = { item_id: string; message_id: string; part_ids: MessagePartIdsModel; role: string; content: string; file_paths?: string[]; image_attachments?: ImageAttachmentModel[]; markdown: boolean; historical: boolean; created_at: string };

export type ImageAttachmentModel = { upload_id: string; name: string; mime_type: string; byte_count: number; preview_url: string };

export type InputStateSseEventModel = { seq: number; created_at: string; type: "input_state"; payload: InputStateSseEventPayloadModel };

export type InputStateSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; enabled: boolean };

export type LiveSessionBoundSseEventModel = { seq: number; created_at: string; type: "live_session_bound"; payload: LiveSessionLifecycleSseEventPayloadModel };

export type LiveSessionEndedSseEventModel = { seq: number; created_at: string; type: "live_session_ended"; payload: LiveSessionLifecycleSseEventPayloadModel };

export type LiveSessionInputRequest = { text?: string; file_paths?: string[]; image_paths?: string[]; image_upload_ids?: string[]; profile_id?: string | null; interactive_mode?: boolean };

export type LiveSessionLifecycleSseEventPayloadModel = { live_session: LiveSessionModel };

export type LiveSessionModel = { live_session_id: string; session_id: string | null; resume_session_id?: string | null; task_id: string | null; kind: "session" | "task"; project_dir: string; provider_id: string | null; profile_id: string | null; provider: string; model: string; reasoning_effort: string; compact_threshold: number; created_at: string; status: "idle" | "starting" | "running" | "waiting_for_input" | "ended" | "failed" | "stale"; exit_code: number | null; fatal_error: string | null; ended_at: string | null; last_event_seq?: number };

export type LiveSessionResponse = { session: LiveSessionModel };

export type LiveSessionShellCommandRequest = { command?: string };

export type LiveSessionSnapshotModel = { live_session_id: string; session_id: string | null; runtime: RuntimeSummaryModel | null; input_enabled: boolean; wait_message: string | null; processing: ProcessingStateModel | null; session_usage: Record<string, unknown> | null; turn_usage: Record<string, unknown> | null; session_ended: boolean; fatal_error: string | null; pending_user_questions: PendingUserQuestionsModel | null; items: Record<string, unknown>[]; sub_agents: Record<string, Record<string, string>>; last_event_seq: number };

export type LiveSessionStartedSseEventModel = { seq: number; created_at: string; type: "live_session_started"; payload: LiveSessionLifecycleSseEventPayloadModel };

export type LiveSessionUpdatedSseEventModel = { seq: number; created_at: string; type: "live_session_updated"; payload: LiveSessionLifecycleSseEventPayloadModel };

export type MessageAddedSseEventModel = { seq: number; created_at: string; type: "message_added"; payload: MessageAddedSseEventPayloadModel };

export type MessageAddedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; item_id: string; role: "user" | "assistant" | "notice" | "error" | "debug"; content: string; markdown?: boolean; message_id?: string | null; part_ids?: MessagePartIdsModel | null; file_paths?: string[]; image_attachments?: ImageAttachmentModel[]; historical?: boolean | null; created_at?: string | null; sub_agent_id?: string | null };

export type MessagePartIdsModel = { content: string; file_paths?: string[]; image_attachments?: string[] };

export type MessageRekeyedSseEventModel = { seq: number; created_at: string; type: "message_rekeyed"; payload: MessageRekeyedSseEventPayloadModel };

export type MessageRekeyedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; old_item_id: string; item: MessageAddedSseEventPayloadModel };

export type MessageRemovedSseEventModel = { seq: number; created_at: string; type: "message_removed"; payload: MessageRemovedSseEventPayloadModel };

export type MessageRemovedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; item_id: string; restore_input?: string | null };

export type ModelProfileListResponse = { model_profiles: ModelProfileViewModel[]; active_profile_id: string | null; config_revision: string };

export type ModelProfileMutationRequest = { id?: string | null; name: string; provider_id: string; model?: string | null; sub_agent_model?: string | null; reasoning_effort?: string | null; max_tokens?: number | null; service_tier?: string | null; web_search?: boolean | null; max_tool_workers?: number | null; max_retries?: number | null; compact_threshold?: number | null; compact_tail_turns?: number | null; compact_preserve_recent_tokens?: number | null; compact_tool_output_max_chars?: number | null };

export type ModelProfileProviderModel = { id: string; name: string; kind: string };

export type ModelProfileResponse = { model_profile: ModelProfileViewModel; config_revision: string };

export type ModelProfileUpdateRequest = { name?: string | null; provider_id?: string | null; model?: string | null; sub_agent_model?: string | null; reasoning_effort?: string | null; max_tokens?: number | null; service_tier?: string | null; web_search?: boolean | null; max_tool_workers?: number | null; max_retries?: number | null; compact_threshold?: number | null; compact_tail_turns?: number | null; compact_preserve_recent_tokens?: number | null; compact_tool_output_max_chars?: number | null };

export type ModelProfileViewModel = { id: string; name: string; provider_id: string; provider: ModelProfileProviderModel; model: string | null; sub_agent_model: string | null; reasoning_effort: string | null; max_tokens: number | null; service_tier: string | null; web_search: boolean | null; max_tool_workers: number | null; max_retries: number | null; compact_threshold: number | null; compact_tail_turns: number | null; compact_preserve_recent_tokens: number | null; compact_tool_output_max_chars: number | null; is_active_default: boolean; resolved_runtime: ResolvedRuntimeViewModel };

export type NewSessionRequest = { profile_id?: string | null };

export type ObservabilityEventModel = { run_session_id: string; session_id: string | null; step_index: number; event_type: string; timestamp: string; duration_ms: number | null; provider: string | null; model: string | null; url: string | null; request_config: unknown | null; request_payload: unknown | null; response_payload: unknown | null; tool_name: string | null; tool_call_id: string | null; tool_input: unknown | null; tool_output: unknown | null; tool_duration_ms: number | null; prompt_tokens: number | null; completion_tokens: number | null; total_tokens: number | null; status_code: number | null; success: boolean | null; error_message: string | null; metadata: unknown | null };

export type PendingUserQuestionModel = { question_id: string; question: string; suggestions: string[]; recommended_suggestion_index?: 0 };

export type PendingUserQuestionsModel = { prompt_id: string; questions: PendingUserQuestionModel[] };

export type ProcessingStateModel = { active: boolean; phase?: "starting" | "model_wait" | "tool_execution" | "finalizing" | "interrupting" | "retry_wait" | null; message?: string | null; active_tool_count?: number | null };

export type ProcessingStateSseEventModel = { seq: number; created_at: string; type: "processing_state"; payload: ProcessingStateModel };

export type ProviderAuthFlowResponse = { provider: ProviderViewModel; auth_status: ProviderAuthStatusModel; flow: ProviderAuthFlowViewModel; session?: ProviderAuthSessionModel | null };

export type ProviderAuthFlowStartRequest = { method: "browser" | "device" };

export type ProviderAuthFlowViewModel = { flow_id: string; provider_id: string; backend: string; method: "browser" | "device"; status: "pending" | "completed" | "failed"; authorization_url?: string | null; callback_url?: string | null; verification_url?: string | null; user_code?: string | null; interval_seconds?: number | null; error_message?: string | null; created_at: string; updated_at: string };

export type ProviderAuthImportRequest = { access_token: string; refresh_token?: string | null; account_id?: string | null; email?: string | null; plan_type?: string | null; expires_at?: number | null; id_token?: string | null };

export type ProviderAuthLogoutResponse = { provider: ProviderViewModel; auth_status: ProviderAuthStatusModel; removed: boolean };

export type ProviderAuthModeMetadataModel = { label: string; account_label: string | null; supported_methods: ("browser" | "device")[] };

export type ProviderAuthResponse = { provider: ProviderViewModel; auth_status: ProviderAuthStatusModel; session?: ProviderAuthSessionModel | null };

export type ProviderAuthSessionModel = { provider_id: string; backend: string; expires_at: number | null; account_id: string | null; email: string | null; plan_type: string | null };

export type ProviderAuthStatusModel = { auth_mode: string; backend: string | null; session_status: string; has_session: boolean; can_refresh: boolean; account_id: string | null; email: string | null; plan_type: string | null; expires_at: number | null };

export type ProviderBreakdownModel = { provider: string | null; model: string | null; run_count: number; total_tokens: number; total_cost: number; avg_duration_ms: number | null; error_count: number; total_api_calls: number; total_tool_calls: number };

export type ProviderKindMetadataModel = { label: string; description?: string | null; default_auth_mode: string; auth_modes: string[]; auth_mode_metadata: Record<string, ProviderAuthModeMetadataModel>; default_model: string; default_sub_agent_model: string | null; default_responses_url: string | null; default_generic_api_url: string | null; supports_responses_url: boolean; supports_generic_api_url: boolean; supports_service_tier: boolean; supports_native_web_search: boolean; supports_image_inputs: boolean };

export type ProviderListResponse = { providers: ProviderViewModel[]; config_revision: string };

export type ProviderModelFetchErrorModel = { code: string; message: string; status_code?: number | null };

export type ProviderModelListResponse = { provider_id: string; provider_kind: string; discovery_supported: boolean; manual_entry_required: boolean; models: ProviderModelViewModel[]; error?: ProviderModelFetchErrorModel | null };

export type ProviderModelViewModel = { id: string; display_name?: string | null; created?: number | string | null; owned_by?: string | null; input_modalities?: string[]; output_modalities?: string[]; aliases?: string[]; supports_reasoning_effort?: boolean | null };

export type ProviderMutationRequest = { id?: string | null; name: string; kind: string; auth_mode?: string | null; api_key?: string | null; api_key_env?: string | null; responses_url?: string | null; generic_api_url?: string | null };

export type ProviderResponse = { provider: ProviderViewModel; config_revision: string };

export type ProviderUpdateRequest = { name?: string | null; kind?: string | null; auth_mode?: string | null; api_key?: string | null; api_key_env?: string | null; responses_url?: string | null; generic_api_url?: string | null };

export type ProviderUsageLimitsResponse = { provider_id: string; provider_kind: string; account_label: string | null; plan_type: string | null; fetched_at: string; buckets: UsageLimitBucketModel[] };

export type ProviderViewModel = { id: string; name: string; kind: string; auth_mode: string; responses_url: string | null; generic_api_url: string | null; secret_source: "none" | "plaintext" | "env_var"; secret_env_var: string | null; has_secret: boolean; auth_status: ProviderAuthStatusModel };

export type QuestionAnswerRequest = { question_id: string; answer: string; selected_suggestion_index?: number | null; custom?: boolean };

export type ResolvedRuntimeViewModel = { provider: string; provider_id: string; profile_id: string; model: string; sub_agent_model: string | null; reasoning_effort: string; max_tokens: number; service_tier: string | null; web_search: boolean; max_tool_workers: number; max_retries: number; compact_threshold: number; compact_tail_turns: number; compact_preserve_recent_tokens: number; compact_tool_output_max_chars: number; responses_url: string; generic_api_url: string; supports_image_inputs: boolean };

export type RunSessionDetailResponse = { run: RunSessionModel; events: ObservabilityEventModel[] };

export type RunSessionModel = { run_session_id: string; session_id: string | null; parent_run_session_id: string | null; agent_name: string | null; agent_type: string | null; provider: string | null; provider_id: string | null; profile_id: string | null; model: string | null; status: "started" | "completed" | "interrupted" | "failed" | "starting" | "running" | "waiting_for_input" | "ended" | "stale"; started_at: string; ended_at: string | null; total_duration_ms: number | null; input_tokens: number; cached_input_tokens: number; cache_write_tokens: number; cache_write_1h_tokens: number; output_tokens: number; reasoning_tokens: number; tool_use_tokens: number; provider_total_tokens: number; estimated_cost_usd: number; total_tool_calls: number; total_api_calls: number; error_count: number; kind?: string; task_id?: string | null; project_dir?: string | null; last_event_seq?: number; snapshot?: unknown | null; exit_code?: number | null; fatal_error?: string | null; metadata: unknown | null };

export type RuntimeSummaryModel = { provider: string | null; provider_id: string | null; profile_id: string | null; model: string | null; reasoning_effort: string | null; compact_threshold?: number | null };

export type ServerConnectedSseEventModel = { seq: number; created_at: string; type: "server.connected"; payload: EmptyPayloadModel };

export type ServerHeartbeatSseEventModel = { seq: number; created_at: string; type: "server.heartbeat"; payload: EmptyPayloadModel };

export type ServerReplayIncompleteSseEventModel = { seq: number; created_at: string; type: "server.replay_incomplete"; payload: ServerReplayIncompleteSseEventPayloadModel };

export type ServerReplayIncompleteSseEventPayloadModel = { reason: "cursor_too_old" | "cursor_ahead" | "subscriber_queue_overflow"; requested_since: number; resolved_since: number; oldest_available_seq?: number | null; latest_seq: number; snapshot_required: boolean };

export type SessionCreatedSseEventModel = { seq: number; created_at: string; type: "session_created"; payload: SessionCreatedSseEventPayloadModel };

export type SessionCreatedSseEventPayloadModel = { session: SessionRecordModel };

export type SessionDetailResponse = { session: SessionRecordModel; status?: "idle" | "starting" | "running" | "waiting_for_input" | "ended" | "failed" | "stale"; history_items: HistoryItemModel[]; timeline?: LiveSessionSnapshotModel | null; live_session?: LiveSessionModel | null; active_live_session?: LiveSessionModel | null; active_run?: LiveSessionModel | null };

export type SessionIdentitySseEventModel = { seq: number; created_at: string; type: "session_identity"; payload: SessionIdentitySseEventPayloadModel };

export type SessionIdentitySseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null };

export type SessionImageUploadResponse = { uploads: ImageAttachmentModel[] };

export type SessionRecordModel = { session_id: string; directory: string; provider: string; provider_id: string | null; model: string; profile_id: string | null; previous_id: string | null; title: string; total_tokens: number; input_tokens: number; output_tokens: number; cost_usd: number; created_at: string; updated_at: string; status?: "idle" | "starting" | "running" | "waiting_for_input" | "ended" | "failed" | "stale"; active_run_id?: string | null; active_live_session_id?: string | null; task_id?: string | null };

export type SessionResetSseEventModel = { seq: number; created_at: string; type: "session_reset"; payload: EmptyPayloadModel };

export type SessionResponse = { session: SessionRecordModel };

export type SessionRunsResponse = { runs: RunSessionModel[] };

export type SessionRuntimeUpdatedSseEventModel = { seq: number; created_at: string; type: "session_runtime_updated"; payload: SessionRuntimeUpdatedSseEventPayloadModel };

export type SessionRuntimeUpdatedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; provider_id?: string | null; profile_id?: string | null; provider: string; model: string; reasoning_effort: string; compact_threshold: number };

export type SessionStateSseEventModel = { seq: number; created_at: string; type: "session_state"; payload: SessionStateSseEventPayloadModel };

export type SessionStateSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; state: "starting" | "running" | "ended"; exit_code?: number | null; fatal_error?: string | null };

export type SessionUpdatedSseEventModel = { seq: number; created_at: string; type: "session_updated"; payload: SessionUpdatedSseEventPayloadModel };

export type SessionUpdatedSseEventPayloadModel = { session: SessionRecordModel };

export type SessionsResponse = { sessions: SessionRecordModel[] };

export type SlashCommandItemModel = { name: string; description: string; kind: "local_command" | "command" };

export type SlashCommandSearchResponse = { items: SlashCommandItemModel[] };

export type SubAgentStateSseEventModel = { seq: number; created_at: string; type: "sub_agent_state"; payload: SubAgentStateSseEventPayloadModel };

export type SubAgentStateSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; sub_agent_id: string; title: string; status: string };

export type SubmitQuestionResponseRequest = { prompt_id: string; answers?: QuestionAnswerRequest[] };

export type TaskDeletedSseEventModel = { seq: number; created_at: string; type: "task_deleted"; payload: TaskDeletedSseEventPayloadModel };

export type TaskDeletedSseEventPayloadModel = { task_id: string };

export type TaskImageUploadResponse = { uploads: ImageAttachmentModel[] };

export type TaskRecordModel = { task_id: string; directory: string; title: string; prompt: string; stage: string; position: number; project_dir: string; session_id: string | null; profile_id: string | null; run_status: "idle" | "running" | "completed" | "failed"; last_result_summary: string; created_at: string; updated_at: string; last_run_started_at: string | null; last_run_finished_at: string | null; image_attachments?: ImageAttachmentModel[]; runtime_summary: RuntimeSummaryModel };

export type TaskResponse = { task: TaskRecordModel };

export type TaskUpdatedSseEventModel = { seq: number; created_at: string; type: "task_updated"; payload: TaskUpdatedSseEventPayloadModel };

export type TaskUpdatedSseEventPayloadModel = { task: TaskRecordModel };

export type TasksResponse = { tasks: TaskRecordModel[] };

export type ThinkingUpdatedSseEventModel = { seq: number; created_at: string; type: "thinking_updated"; payload: ThinkingUpdatedSseEventPayloadModel };

export type ThinkingUpdatedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; item_id: string; title: string; content: string; sub_agent_id?: string | null };

export type TokenUsagePayloadModel = { input_tokens: number; cached_input_tokens: number; cache_write_tokens: number; cache_write_1h_tokens: number; output_tokens: number; reasoning_tokens: number; tool_use_tokens: number; provider_total_tokens: number; sub_agent_input_tokens: number; sub_agent_output_tokens: number; sub_agent_reasoning_tokens: number; sub_agent_tool_use_tokens: number; sub_agent_provider_total_tokens: number; sub_agent_cost_usd: number; context_tokens: number; total_tokens: number; estimated_cost_usd: number; main_agent_total_tokens: number; sub_agent_total_tokens: number; model: string; service_tier: string };

export type ToolCallMetadataModel = { tool_name?: string | null; path?: string | null; operation?: string | null; success?: boolean | null; detail?: string | null; diff?: string | null; diff_line_numbers?: DiffLineNumberModel[] | null; call_id?: string | null; status?: "running" | "completed" | "failed" | null; arguments?: Record<string, unknown> | string | null; result?: Record<string, unknown> | string | null; error?: unknown; command?: string | null; working_directory?: string | null; timeout_ms?: number | string | null; exit_code?: number | null; timed_out?: boolean | null };

export type ToolGroupAddedSseEventModel = { seq: number; created_at: string; type: "tool_group_added"; payload: ToolGroupAddedSseEventPayloadModel };

export type ToolGroupAddedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; item_id: string; label: string; status?: "running" | "completed" | null; items?: ToolGroupEntryModel[]; sub_agent_id?: string | null };

export type ToolGroupEntryModel = { text: string; classes?: string; metadata?: ToolCallMetadataModel | null };

export type UpdateBoardStagesRequest = { board_stages: BoardStageUpdateModel[] };

export type UpdateSessionRequest = { title: string };

export type UpdateTaskRequest = { title?: string | null; prompt?: string | null; stage?: string | null; position?: number | null; project_dir?: string | null; session_id?: string | null; profile_id?: string | null; image_upload_ids?: string[] | null };

export type UsageLimitBucketModel = { id: string; label: string; unlimited: boolean; overage_allowed: boolean; overage_count: number; status: "ok" | "warning" | "exhausted" | "unknown"; credits?: UsageLimitCreditsModel | null; windows: UsageLimitWindowModel[] };

export type UsageLimitCreditsModel = { has_credits?: boolean | null; unlimited?: boolean | null; balance?: string | null };

export type UsageLimitWindowModel = { name: string; used_percent?: number | null; remaining_percent?: number | null; window_minutes?: number | null; resets_at?: number | null; reset_at_iso?: string | null; used_requests?: number | null; total_requests?: number | null; remaining_requests?: number | null };

export type UsageUpdatedSseEventModel = { seq: number; created_at: string; type: "usage_updated"; payload: UsageUpdatedSseEventPayloadModel };

export type UsageUpdatedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; scope: "session" | "turn"; usage: TokenUsagePayloadModel; elapsed_seconds?: number | null; sub_agent_id?: string | null };

export type UserQuestionsRequestedSseEventModel = { seq: number; created_at: string; type: "user_questions_requested"; payload: PendingUserQuestionsModel };

export type UserQuestionsResolvedSseEventModel = { seq: number; created_at: string; type: "user_questions_resolved"; payload: UserQuestionsResolvedSseEventPayloadModel };

export type UserQuestionsResolvedSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; prompt_id: string };

export type ValidationError = { loc: (string | number)[]; msg: string; type: string; input?: unknown; ctx?: Record<string, unknown> };

export type WaitStateSseEventModel = { seq: number; created_at: string; type: "wait_state"; payload: WaitStateSseEventPayloadModel };

export type WaitStateSseEventPayloadModel = { live_session_id?: string | null; session_id?: string | null; resume_session_id?: string | null; active: boolean; message?: string | null };

export type AppSseEventModel = SessionCreatedSseEventModel | SessionUpdatedSseEventModel | BoardStagesUpdatedSseEventModel | TaskUpdatedSseEventModel | TaskDeletedSseEventModel | LiveSessionStartedSseEventModel | LiveSessionUpdatedSseEventModel | LiveSessionBoundSseEventModel | LiveSessionEndedSseEventModel;

export type SessionSseEventModel = SessionResetSseEventModel | SessionIdentitySseEventModel | InputStateSseEventModel | WaitStateSseEventModel | ProcessingStateSseEventModel | UserQuestionsRequestedSseEventModel | UserQuestionsResolvedSseEventModel | UsageUpdatedSseEventModel | MessageAddedSseEventModel | MessageRekeyedSseEventModel | MessageRemovedSseEventModel | ThinkingUpdatedSseEventModel | ToolGroupAddedSseEventModel | SubAgentStateSseEventModel | SessionStateSseEventModel | SessionRuntimeUpdatedSseEventModel;

export type SseControlEventModel = ServerConnectedSseEventModel | ServerHeartbeatSseEventModel | ServerReplayIncompleteSseEventModel;

export type SseEventModel = ServerConnectedSseEventModel | ServerHeartbeatSseEventModel | ServerReplayIncompleteSseEventModel | SessionResetSseEventModel | SessionIdentitySseEventModel | InputStateSseEventModel | WaitStateSseEventModel | ProcessingStateSseEventModel | UserQuestionsRequestedSseEventModel | UserQuestionsResolvedSseEventModel | UsageUpdatedSseEventModel | MessageAddedSseEventModel | MessageRekeyedSseEventModel | MessageRemovedSseEventModel | ThinkingUpdatedSseEventModel | ToolGroupAddedSseEventModel | SubAgentStateSseEventModel | SessionStateSseEventModel | SessionRuntimeUpdatedSseEventModel | SessionCreatedSseEventModel | SessionUpdatedSseEventModel | BoardStagesUpdatedSseEventModel | TaskUpdatedSseEventModel | TaskDeletedSseEventModel | LiveSessionStartedSseEventModel | LiveSessionUpdatedSseEventModel | LiveSessionBoundSseEventModel | LiveSessionEndedSseEventModel;

export type ApiOperationResponses = {
  "GET /api/board/stages": BoardStagesResponse;
  "PUT /api/board/stages": BoardStagesResponse;
  "GET /api/bootstrap": BootstrapResponse;
  "PUT /api/config/active-model-profile": ActiveProfileResponse;
  "GET /api/config/bootstrap": ConfigBootstrapResponse;
  "GET /api/config/commands": CommandListResponse;
  "GET /api/config/model-profiles": ModelProfileListResponse;
  "POST /api/config/model-profiles": ModelProfileResponse;
  "DELETE /api/config/model-profiles/{profile_id}": void;
  "PATCH /api/config/model-profiles/{profile_id}": ModelProfileResponse;
  "GET /api/config/providers": ProviderListResponse;
  "POST /api/config/providers": ProviderResponse;
  "DELETE /api/config/providers/{provider_id}": void;
  "PATCH /api/config/providers/{provider_id}": ProviderResponse;
  "GET /api/config/providers/{provider_id}/models": ProviderModelListResponse;
  "GET /api/dashboard/stats": DashboardStatsResponse;
  "GET /api/events/sessions/{session_id}": unknown;
  "GET /api/events/{stream_id}": unknown;
  "GET /api/files/search": FileMentionSearchResponse;
  "DELETE /api/provider-auth/{provider_id}": ProviderAuthLogoutResponse;
  "GET /api/provider-auth/{provider_id}": ProviderAuthResponse;
  "POST /api/provider-auth/{provider_id}/flows": ProviderAuthFlowResponse;
  "GET /api/provider-auth/{provider_id}/flows/{flow_id}": ProviderAuthFlowResponse;
  "POST /api/provider-auth/{provider_id}/flows/{flow_id}/poll": ProviderAuthFlowResponse;
  "POST /api/provider-auth/{provider_id}/import": ProviderAuthResponse;
  "POST /api/provider-auth/{provider_id}/refresh": ProviderAuthResponse;
  "GET /api/provider-auth/{provider_id}/usage-limits": ProviderUsageLimitsResponse;
  "GET /api/runs": AllRunsResponse;
  "GET /api/runs/{run_session_id}": RunSessionDetailResponse;
  "GET /api/sessions": SessionsResponse;
  "POST /api/sessions": SessionResponse;
  "POST /api/sessions/expand-input": ExpandInputResponse;
  "DELETE /api/sessions/{session_id}": void;
  "GET /api/sessions/{session_id}": SessionDetailResponse;
  "PATCH /api/sessions/{session_id}": SessionResponse;
  "POST /api/sessions/{session_id}/images": SessionImageUploadResponse;
  "POST /api/sessions/{session_id}/interrupt": LiveSessionResponse;
  "POST /api/sessions/{session_id}/messages": LiveSessionResponse;
  "POST /api/sessions/{session_id}/new-session": LiveSessionResponse;
  "PUT /api/sessions/{session_id}/profile": LiveSessionResponse;
  "POST /api/sessions/{session_id}/question-response": LiveSessionResponse;
  "GET /api/sessions/{session_id}/runs": SessionRunsResponse;
  "POST /api/sessions/{session_id}/runs": LiveSessionResponse;
  "POST /api/sessions/{session_id}/shell-command": LiveSessionResponse;
  "GET /api/slash-commands/search": SlashCommandSearchResponse;
  "GET /api/tasks": TasksResponse;
  "POST /api/tasks": TaskResponse;
  "POST /api/tasks/images": TaskImageUploadResponse;
  "DELETE /api/tasks/{task_id}": void;
  "PATCH /api/tasks/{task_id}": TaskResponse;
  "POST /api/tasks/{task_id}/run": TaskResponse;
  "GET /api/uploads/{upload_id}": unknown;
};

export type ApiJsonRequestBodies = {
  "PUT /api/board/stages": UpdateBoardStagesRequest;
  "PUT /api/config/active-model-profile": ActiveProfileRequest;
  "POST /api/config/model-profiles": ModelProfileMutationRequest;
  "PATCH /api/config/model-profiles/{profile_id}": ModelProfileUpdateRequest;
  "POST /api/config/providers": ProviderMutationRequest;
  "PATCH /api/config/providers/{provider_id}": ProviderUpdateRequest;
  "POST /api/provider-auth/{provider_id}/flows": ProviderAuthFlowStartRequest;
  "POST /api/provider-auth/{provider_id}/import": ProviderAuthImportRequest;
  "POST /api/sessions": CreateSessionRequest;
  "POST /api/sessions/expand-input": ExpandInputRequest;
  "PATCH /api/sessions/{session_id}": UpdateSessionRequest;
  "POST /api/sessions/{session_id}/messages": LiveSessionInputRequest;
  "POST /api/sessions/{session_id}/new-session": NewSessionRequest;
  "PUT /api/sessions/{session_id}/profile": ActiveProfileRequest;
  "POST /api/sessions/{session_id}/question-response": SubmitQuestionResponseRequest;
  "POST /api/sessions/{session_id}/runs": LiveSessionInputRequest;
  "POST /api/sessions/{session_id}/shell-command": LiveSessionShellCommandRequest;
  "POST /api/tasks": CreateTaskRequest;
  "PATCH /api/tasks/{task_id}": UpdateTaskRequest;
};

export type ApiOperationPathParams = {
  "DELETE /api/config/model-profiles/{profile_id}": { profile_id: string };
  "PATCH /api/config/model-profiles/{profile_id}": { profile_id: string };
  "DELETE /api/config/providers/{provider_id}": { provider_id: string };
  "PATCH /api/config/providers/{provider_id}": { provider_id: string };
  "GET /api/config/providers/{provider_id}/models": { provider_id: string };
  "GET /api/events/sessions/{session_id}": { session_id: string };
  "GET /api/events/{stream_id}": { stream_id: string };
  "DELETE /api/provider-auth/{provider_id}": { provider_id: string };
  "GET /api/provider-auth/{provider_id}": { provider_id: string };
  "POST /api/provider-auth/{provider_id}/flows": { provider_id: string };
  "GET /api/provider-auth/{provider_id}/flows/{flow_id}": { provider_id: string; flow_id: string };
  "POST /api/provider-auth/{provider_id}/flows/{flow_id}/poll": { provider_id: string; flow_id: string };
  "POST /api/provider-auth/{provider_id}/import": { provider_id: string };
  "POST /api/provider-auth/{provider_id}/refresh": { provider_id: string };
  "GET /api/provider-auth/{provider_id}/usage-limits": { provider_id: string };
  "GET /api/runs/{run_session_id}": { run_session_id: string };
  "DELETE /api/sessions/{session_id}": { session_id: string };
  "GET /api/sessions/{session_id}": { session_id: string };
  "PATCH /api/sessions/{session_id}": { session_id: string };
  "POST /api/sessions/{session_id}/images": { session_id: string };
  "POST /api/sessions/{session_id}/interrupt": { session_id: string };
  "POST /api/sessions/{session_id}/messages": { session_id: string };
  "POST /api/sessions/{session_id}/new-session": { session_id: string };
  "PUT /api/sessions/{session_id}/profile": { session_id: string };
  "POST /api/sessions/{session_id}/question-response": { session_id: string };
  "GET /api/sessions/{session_id}/runs": { session_id: string };
  "POST /api/sessions/{session_id}/runs": { session_id: string };
  "POST /api/sessions/{session_id}/shell-command": { session_id: string };
  "DELETE /api/tasks/{task_id}": { task_id: string };
  "PATCH /api/tasks/{task_id}": { task_id: string };
  "POST /api/tasks/{task_id}/run": { task_id: string };
  "GET /api/uploads/{upload_id}": { upload_id: string };
};

export type ApiOperationQueryParams = {
  "GET /api/dashboard/stats": { start_date?: string | null; end_date?: string | null; scope?: string };
  "GET /api/events/sessions/{session_id}": { since?: number; live_session_id?: string | null };
  "GET /api/events/{stream_id}": { since?: number };
  "GET /api/files/search": { q?: string; limit?: number };
  "GET /api/runs": { limit?: number; offset?: number; status?: string | null; provider?: string | null; model?: string | null; start_date?: string | null; end_date?: string | null; sort_by?: string; sort_dir?: string; scope?: string };
  "GET /api/runs/{run_session_id}": { scope?: string };
  "GET /api/sessions": { limit?: number };
  "GET /api/slash-commands/search": { q?: string; limit?: number };
};

export type ApiOperation = keyof ApiOperationResponses;

export type ApiResponse<T extends ApiOperation> = ApiOperationResponses[T];

export type ApiJsonBody<T extends keyof ApiJsonRequestBodies> = ApiJsonRequestBodies[T];

export type ApiPathParams<T extends keyof ApiOperationPathParams> = ApiOperationPathParams[T];

export type ApiQueryParams<T extends keyof ApiOperationQueryParams> = ApiOperationQueryParams[T];
