from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from pbi_agent.config import Settings
from pbi_agent.web.serve import create_app


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "webapp" / "src" / "api-types.generated.ts"


def main() -> None:
    OUTPUT.write_text(render_api_types(), encoding="utf-8")


def render_api_types() -> str:
    app = create_app(Settings(api_key="schema", provider="openai", model="schema"))
    schemas = app.openapi().get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise RuntimeError("OpenAPI components.schemas is missing.")

    lines = [
        "// Generated by scripts/generate_api_types.py. Do not edit.",
        "/* eslint-disable */",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if not isinstance(schema, dict):
            continue
        lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    return "\n".join(lines)


def ts_type(schema: dict[str, Any]) -> str:
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return ref.rsplit("/", 1)[-1]

    for key, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        variants = schema.get(key)
        if isinstance(variants, list):
            return separator.join(
                _unique(ts_type(item) for item in variants if isinstance(item, dict))
            )

    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(_literal(value) for value in enum) or "never"
    if "const" in schema:
        return _literal(schema["const"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_unique(_scalar_type(item, schema) for item in schema_type))
    if schema_type == "array":
        items = schema.get("items")
        item_type = ts_type(items) if isinstance(items, dict) else "unknown"
        return f"{_wrap_union(item_type)}[]"
    if schema_type == "object" or "properties" in schema:
        return object_type(schema)
    if isinstance(schema_type, str):
        return _scalar_type(schema_type, schema)
    return "unknown"


def object_type(schema: dict[str, Any]) -> str:
    properties = schema.get("properties")
    required = schema.get("required")
    if not isinstance(properties, dict):
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"
        return "Record<string, unknown>"

    required_names = (
        {item for item in required if isinstance(item, str)}
        if isinstance(required, list)
        else set()
    )
    fields: list[str] = []
    for name, value in properties.items():
        if not isinstance(name, str) or not isinstance(value, dict):
            continue
        optional = "" if name in required_names else "?"
        fields.append(f"{ts_property(name)}{optional}: {ts_type(value)}")

    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        fields.append(f"[key: string]: {ts_type(additional)}")
    if additional is True:
        fields.append("[key: string]: unknown")
    return "{ " + "; ".join(fields) + " }"


def ts_property(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name):
        return name
    return json.dumps(name)


def _scalar_type(schema_type: str, schema: dict[str, Any]) -> str:
    del schema
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(value)


def _unique(values: Any) -> list[str]:
    result: list[str] = []
    for value in values:
        if value and value not in result:
            result.append(value)
    return result


def _wrap_union(value: str) -> str:
    return f"({value})" if " | " in value or " & " in value else value


if __name__ == "__main__":
    main()
