from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from pbi_agent.config import Settings
from pbi_agent.web.api.schemas.events import API_TYPE_ALIASES, EXTRA_API_TYPE_MODELS
from pbi_agent.web.serve import create_app


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "webapp" / "src" / "api-types.generated.ts"


def main() -> None:
    OUTPUT.write_text(render_api_types(), encoding="utf-8")


def render_api_types() -> str:
    app = create_app(Settings(api_key="schema", provider="openai", model="schema"))
    raw_schemas = app.openapi().get("components", {}).get("schemas", {})
    if not isinstance(raw_schemas, dict):
        raise RuntimeError("OpenAPI components.schemas is missing.")
    schemas = dict(raw_schemas)
    for model_type in EXTRA_API_TYPE_MODELS:
        schema = model_type.model_json_schema(
            ref_template="#/components/schemas/{model}"
        )
        defs = schema.pop("$defs", {})
        if isinstance(defs, dict):
            schemas.update(defs)
        schemas[model_type.__name__] = schema

    lines = [
        "// Generated by scripts/generate_api_types.py. Do not edit.",
        "/* eslint-disable */",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if not isinstance(schema, dict):
            continue
        lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    for name, model_names in sorted(API_TYPE_ALIASES.items()):
        lines.append(f"export type {name} = {' | '.join(model_names)};")
        lines.append("")
    lines.extend(render_api_operations(app.openapi()))
    return "\n".join(lines)


def render_api_operations(openapi: dict[str, Any]) -> list[str]:
    paths = openapi.get("paths", {})
    if not isinstance(paths, dict):
        raise RuntimeError("OpenAPI paths is missing.")

    response_fields: list[str] = []
    json_body_fields: list[str] = []
    for path, path_item in sorted(paths.items()):
        if not isinstance(path, str) or not path.startswith("/api/"):
            continue
        if not isinstance(path_item, dict):
            continue
        for method in ("delete", "get", "patch", "post", "put"):
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            operation_key = f"{method.upper()} {path}"
            response_fields.append(
                f"  {ts_property(operation_key)}: {operation_response_type(operation)};"
            )
            json_body_type = operation_json_body_type(operation)
            if json_body_type is not None:
                json_body_fields.append(
                    f"  {ts_property(operation_key)}: {json_body_type};"
                )

    lines = [
        "export type ApiOperationResponses = {",
        *response_fields,
        "};",
        "",
        "export type ApiJsonRequestBodies = {",
        *json_body_fields,
        "};",
        "",
        "export type ApiOperation = keyof ApiOperationResponses;",
        "",
        "export type ApiResponse<T extends ApiOperation> = ApiOperationResponses[T];",
        "",
        "export type ApiJsonBody<T extends keyof ApiJsonRequestBodies> = ApiJsonRequestBodies[T];",
        "",
    ]
    return lines


def operation_response_type(operation: dict[str, Any]) -> str:
    responses = operation.get("responses")
    if not isinstance(responses, dict):
        return "unknown"
    response = select_success_response(responses)
    if response is None:
        return "unknown"
    status_code, response_spec = response
    if status_code == "204":
        return "void"
    if not isinstance(response_spec, dict):
        return "unknown"
    schema = json_content_schema(response_spec.get("content"))
    return ts_type(schema) if schema is not None else "unknown"


def operation_json_body_type(operation: dict[str, Any]) -> str | None:
    request_body = operation.get("requestBody")
    if not isinstance(request_body, dict):
        return None
    schema = json_content_schema(request_body.get("content"))
    return ts_type(schema) if schema is not None else None


def select_success_response(
    responses: dict[str, Any],
) -> tuple[str, Any] | None:
    for status_code in ("200", "201", "202", "204"):
        if status_code in responses:
            return status_code, responses[status_code]
    success_codes = sorted(
        status_code
        for status_code in responses
        if status_code.isdigit() and 200 <= int(status_code) < 300
    )
    if not success_codes:
        return None
    status_code = success_codes[0]
    return status_code, responses[status_code]


def json_content_schema(content: Any) -> dict[str, Any] | None:
    if not isinstance(content, dict):
        return None
    json_content = content.get("application/json")
    if not isinstance(json_content, dict):
        return None
    schema = json_content.get("schema")
    return schema if isinstance(schema, dict) else None


def ts_type(schema: dict[str, Any]) -> str:
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return ref.rsplit("/", 1)[-1]

    for key, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        variants = schema.get(key)
        if isinstance(variants, list):
            return separator.join(
                _unique(ts_type(item) for item in variants if isinstance(item, dict))
            )

    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(_literal(value) for value in enum) or "never"
    if "const" in schema:
        return _literal(schema["const"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_unique(_scalar_type(item, schema) for item in schema_type))
    if schema_type == "array":
        items = schema.get("items")
        item_type = ts_type(items) if isinstance(items, dict) else "unknown"
        return f"{_wrap_union(item_type)}[]"
    if schema_type == "object" or "properties" in schema:
        return object_type(schema)
    if isinstance(schema_type, str):
        return _scalar_type(schema_type, schema)
    return "unknown"


def object_type(schema: dict[str, Any]) -> str:
    properties = schema.get("properties")
    required = schema.get("required")
    if not isinstance(properties, dict):
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"
        return "Record<string, unknown>"

    required_names = (
        {item for item in required if isinstance(item, str)}
        if isinstance(required, list)
        else set()
    )
    fields: list[str] = []
    for name, value in properties.items():
        if not isinstance(name, str) or not isinstance(value, dict):
            continue
        optional = "" if name in required_names else "?"
        fields.append(f"{ts_property(name)}{optional}: {ts_type(value)}")

    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        fields.append(f"[key: string]: {ts_type(additional)}")
    if additional is True:
        fields.append("[key: string]: unknown")
    return "{ " + "; ".join(fields) + " }"


def ts_property(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name):
        return name
    return json.dumps(name)


def _scalar_type(schema_type: str, schema: dict[str, Any]) -> str:
    del schema
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(value)


def _unique(values: Any) -> list[str]:
    result: list[str] = []
    for value in values:
        if value and value not in result:
            result.append(value)
    return result


def _wrap_union(value: str) -> str:
    return f"({value})" if " | " in value or " & " in value else value


if __name__ == "__main__":
    main()
